/*global define*/
define({
    ALL : '全部',
    AUTHOR : '作者',
    CATALOGUE : '目录',
    CATALOGUE_SHOW_MORE : '更多',
    CATALOGUE_SHOW_ALL : '显示全部',
    CATE_FINISHED : '已完结的小说',
    CATE_GIRL : '女生频道',
    CATE_NOVEL : '网络小说',
    CATE_PUBLISHED : '出版图书',
    CATEGORY : '分类',
    DEFAULT_GIRL : '女生频道',
    DEFAULT_NOVEL : '网络小说',
    DEFAULT_PUBLISHED : '出版图书',
    DESCRIPTION : '简介',
    DOWNLOAD_TIPS : '缓存后在手机上阅读',
    DOWNLOADING : '缓存中',
    FINISHED : '已完结',
    META_COUNT : '共 {1} 章',
    META_SOURCE_MORE : '等 {1} 个网站',
    META_WORDS : '{1}字',
    META_UPDATE : '{1}更新',
    NO_DATA : '暂无数据',
    NO_RATING : '暂无评分',
    NO_PREVIEW_CONTENT : '暂无内容。',
    PREVIEW : '章节预览',
    RANK : '排序',
    RATING : '评分',
    READ : '阅读',
    REPORT : '版权举报',
    SERIES : '连载中',
    SOURCE : '来源',
    SUBCATEGORIES : '子类',
    UPDATE_TIME : '更新',
    WORD_COUNT : '字数'
});
