/*global define*/
define({
    ALL : '全部',
    CATE_FINISHED : '已完结的小说',
    CATE_GIRL : '女生频道',
    CATE_NOVEL : '网络小说',
    CATE_PUBLISHED : '出版图书',
    CATEGORY : '分类',
    DEFAULT_GIRL : '女生频道',
    DEFAULT_NOVEL : '网络小说',
    DEFAULT_PUBLISHED : '出版图书',
    FINISHED : '已完结',
    NO_DATA : '暂无数据',
    NO_RATING : '暂无评分',
    RANK : '排序',
    RATING : '评分',
    READ : '阅读',
    SERIES : '连载中',
    SUBCATEGORIES : '子类',
    UPDATE_TIME : '更新',
    WORD_COUNT : '字数',
    REPORT : '版权举报',
    DESCRIPTION : '简介',
    CATALOGUE : '目录',
    CATALOGUE_SHOW_MORE : '更多',
    CATALOGUE_SHOW_ALL : '显示全部',
    PREVIEW : '章节预览',
    META_FINISHED : '已完结 共 {1} 章',
    META_SERIES : '连载中 更新至第 {1} 章',
    META_WORDS : '{1}字',
    META_UPDATE : '{1}更新',
    META_CATE : '分类：{1} / {2}',
    META_CATE_SINGLE : '分类：{1}',
    META_AUTHOR : '作者：{1}',
    META_SOURCE : '来源：{1}',
    META_SOURCE_MORE : '来源：{1}等 {2} 个',
    DOWNLOAD_TIPS : '免费保存全部章节到手机'
});
